apiVersion: v1
entries:
  chrc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-02-11T09:34:56.3705254Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: efcf6279693000ffbf0d1657a8ebaab01cf6e8679621d415ec9523ed1d92016a
    home: chrc.zaakonline.nl
    icon: chrc.zaakonline.nl
    name: chrc
    urls:
    - chrc-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2021-02-11T09:34:56.3821077Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
generated: "2021-02-11T09:34:56.3585919Z"
